// ─── lib/data.js ─────────────────────────────────────────────────────────────
// Centralized mock data that mirrors the Laravel API response shapes.
// Replace any of these with real fetch() calls to your backend.
// ─────────────────────────────────────────────────────────────────────────────

export const CATEGORIES = [
  { id: 1,  slug: "gems-jewelry",          name: "Gems & Jewelry",          emoji: "💎", count: 1200 },
  { id: 2,  slug: "ceylon-tea",            name: "Ceylon Tea",              emoji: "🫖", count: 890  },
  { id: 3,  slug: "apparel-textiles",      name: "Apparel & Textiles",      emoji: "👗", count: 760  },
  { id: 4,  slug: "spices-agriculture",    name: "Spices & Agriculture",    emoji: "🌿", count: 640  },
  { id: 5,  slug: "handicrafts-arts",      name: "Handicrafts & Arts",      emoji: "🏺", count: 520  },
  { id: 6,  slug: "coconut-products",      name: "Coconut Products",        emoji: "🥥", count: 450  },
  { id: 7,  slug: "wood-furniture",        name: "Wood & Furniture",        emoji: "🪵", count: 380  },
  { id: 8,  slug: "seafood-marine",        name: "Seafood & Marine",        emoji: "🐟", count: 320  },
  { id: 9,  slug: "beauty-care",           name: "Beauty & Personal Care",  emoji: "🧴", count: 290  },
  { id: 10, slug: "building-construction", name: "Building & Construction", emoji: "🏗️", count: 410  },
  { id: 11, slug: "industrial-machinery",  name: "Industrial Machinery",    emoji: "⚙️", count: 280  },
  { id: 12, slug: "gifts-novelties",       name: "Gifts & Novelties",       emoji: "🎁", count: 340  },
  { id: 13, slug: "electronics-tech",      name: "Electronics & Tech",      emoji: "💻", count: 195  },
  { id: 14, slug: "health-ayurveda",       name: "Health & Ayurveda",       emoji: "🌺", count: 260  },
];

export const PRODUCTS = [
  {
    id: 1,
    slug: "premium-ceylon-bop-tea",
    category: "Ceylon Tea",
    categorySlug: "ceylon-tea",
    name: "Premium Ceylon Loose Leaf Tea – BOP Grade",
    description:
      "Finest BOP (Broken Orange Pekoe) grade tea sourced from high-grown estates in Nuwara Eliya. Rich amber liquor with robust flavour and brisk finish. Ideal for retail packaging and private label export.",
    price: "$8 – $15",
    priceMin: 8,
    priceMax: 15,
    unit: "/kg",
    minOrder: "50 kg MOQ",
    minOrderQty: 50,
    moqUnit: "kg",
    supplier: "Dilmah Exports Pvt Ltd",
    supplierId: 1,
    location: "Colombo",
    rating: 4.8,
    reviews: 124,
    badge: "Top Supplier",
    tag: "Hot",
    emoji: "🫖",
    bg: "from-emerald-100 to-teal-50",
    certifications: ["ISO 22000", "HACCP", "Rainforest Alliance"],
    leadTime: "7–14 days",
    paymentTerms: "T/T, L/C",
    packaging: "Foil-sealed bags – 1 kg / 5 kg / 25 kg",
    specifications: {
      Grade: "BOP (Broken Orange Pekoe)",
      Origin: "Nuwara Eliya, Sri Lanka",
      Altitude: "1,800–2,200 m",
      Harvest: "January (1st flush) / July (2nd flush)",
      Moisture: "≤ 3.5 %",
      "Particle Size": "0.5–1.0 mm",
    },
    images: ["🫖", "☕", "🍃", "🌿"],
    inStock: true,
    views: 1240,
    inquiries: 89,
  },
  {
    id: 2,
    slug: "natural-blue-sapphire-gia",
    category: "Gems & Jewelry",
    categorySlug: "gems-jewelry",
    name: "Natural Blue Sapphire Gemstone – GIA Certified",
    description:
      "Genuine Ceylon Blue Sapphires sourced from Ratnapura. Each stone comes with GIA certification. Intense cornflower-blue to royal-blue hues with excellent clarity. Both heated and unheated options available.",
    price: "$200 – $2,000",
    priceMin: 200,
    priceMax: 2000,
    unit: "/carat",
    minOrder: "1 carat MOQ",
    minOrderQty: 1,
    moqUnit: "carat",
    supplier: "Lanka Gem Bureau Ltd",
    supplierId: 2,
    location: "Ratnapura",
    rating: 4.9,
    reviews: 67,
    badge: "Verified",
    tag: "Premium",
    emoji: "💎",
    bg: "from-blue-100 to-indigo-50",
    certifications: ["GIA Certified", "SLTB Verified", "AGL Report"],
    leadTime: "3–5 days",
    paymentTerms: "T/T, Western Union, PayPal",
    packaging: "Gem paper folded + gemological box",
    specifications: {
      Type: "Natural Blue Sapphire",
      Origin: "Ratnapura, Sri Lanka (Ceylon)",
      Color: "Medium to Deep Blue",
      Clarity: "Eye-clean to slightly included",
      Cut: "Mixed / Oval / Cushion",
      Treatment: "Unheated or heat-treated (stated on cert)",
    },
    images: ["💎", "💙", "✨", "🔵"],
    inStock: true,
    views: 980,
    inquiries: 45,
  },
  {
    id: 3,
    slug: "handwoven-batik-fabric",
    category: "Apparel & Textiles",
    categorySlug: "apparel-textiles",
    name: "Handwoven Batik Fabric Roll – 100% Cotton",
    description:
      "Traditional Sri Lankan batik fabric by master artisans in Kandy. Each roll features unique hand-stamped wax-resist patterns in vibrant colorfast dyes. GOTS certified organic cotton base fabric.",
    price: "$3 – $8",
    priceMin: 3,
    priceMax: 8,
    unit: "/metre",
    minOrder: "200 m MOQ",
    minOrderQty: 200,
    moqUnit: "metre",
    supplier: "Lanka Batik Creations",
    supplierId: 3,
    location: "Kandy",
    rating: 4.7,
    reviews: 89,
    badge: "Verified",
    tag: "New",
    emoji: "🧵",
    bg: "from-purple-100 to-fuchsia-50",
    certifications: ["GOTS Certified", "OEKO-TEX", "Fair Trade"],
    leadTime: "14–21 days",
    paymentTerms: "T/T, L/C at sight",
    packaging: "50-metre rolls, polywrapped",
    specifications: {
      Material: "100% Organic Cotton",
      Weight: "120–180 GSM",
      Width: "110–115 cm",
      Technique: "Hand block print / Hand wax batik",
      "Dye Type": "Reactive / Vat dyes",
      Shrinkage: "≤ 3 %",
    },
    images: ["🧵", "👗", "🎨", "🌈"],
    inStock: true,
    views: 756,
    inquiries: 62,
  },
  {
    id: 4,
    slug: "organic-ceylon-cinnamon-sticks",
    category: "Spices & Agriculture",
    categorySlug: "spices-agriculture",
    name: "Organic Ceylon Cinnamon Sticks (True Cinnamon)",
    description:
      "Authentic C. zeylanicum – the world's only true cinnamon grown in Sri Lanka's cinnamon belt. Thin-quilled sticks with a delicate sweet flavour. Certified organic, export-ready in multiple grades.",
    price: "$5 – $12",
    priceMin: 5,
    priceMax: 12,
    unit: "/kg",
    minOrder: "25 kg MOQ",
    minOrderQty: 25,
    moqUnit: "kg",
    supplier: "Spice Garden Lanka",
    supplierId: 4,
    location: "Matara",
    rating: 4.9,
    reviews: 203,
    badge: "Top Supplier",
    tag: "Organic",
    emoji: "🌿",
    bg: "from-amber-100 to-yellow-50",
    certifications: ["USDA Organic", "EU Organic", "ISO 9001"],
    leadTime: "10–14 days",
    paymentTerms: "T/T, L/C, DP at sight",
    packaging: "Vacuum sealed – 5 kg / 25 kg cartons",
    specifications: {
      Species: "Cinnamomum zeylanicum (True Ceylon)",
      Grade: "C0 / C1 / C2 / C3 / C4 / C5",
      Moisture: "≤ 12 %",
      "Volatile Oil": "≥ 0.5 %",
      Form: "Quills / Sticks / Powder / Chips",
      Origin: "Matara, Hambantota, Galle Districts",
    },
    images: ["🌿", "🍀", "🌱", "✨"],
    inStock: true,
    views: 2100,
    inquiries: 167,
  },
  {
    id: 5,
    slug: "handcrafted-dumbara-mat",
    category: "Handicrafts & Arts",
    categorySlug: "handicrafts-arts",
    name: "Handcrafted Dumbara Mat – Traditional Weave",
    description:
      "Authentic Dumbara woven mats from the Kandy district artisan community. Crafted from naturally dyed reeds using a centuries-old geometric weaving tradition. Fair-trade certified.",
    price: "$15 – $45",
    priceMin: 15,
    priceMax: 45,
    unit: "/piece",
    minOrder: "20 pcs MOQ",
    minOrderQty: 20,
    moqUnit: "pcs",
    supplier: "Village Craft Collective",
    supplierId: 5,
    location: "Kurunegala",
    rating: 4.6,
    reviews: 41,
    badge: "Verified",
    tag: "Artisan",
    emoji: "🏺",
    bg: "from-orange-100 to-amber-50",
    certifications: ["Fair Trade USA", "WFTO Member"],
    leadTime: "21–30 days",
    paymentTerms: "T/T, PayPal",
    packaging: "Rolled + kraft paper tied, individual hang-tags",
    specifications: {
      Material: "Reed grass (Henrya elata)",
      Dye: "Natural plant-based dyes",
      Sizes: "60×90 cm / 90×120 cm / 120×180 cm",
      Technique: "Traditional Dumbara geometric weave",
      Origin: "Dumbara Valley, Kandy District",
    },
    images: ["🏺", "🎨", "🪢", "🌾"],
    inStock: true,
    views: 430,
    inquiries: 28,
  },
  {
    id: 6,
    slug: "moonstone-pendant-silver",
    category: "Gems & Jewelry",
    categorySlug: "gems-jewelry",
    name: "Moonstone Pendant – Sterling Silver Setting",
    description:
      "Natural adularescent moonstone from Sri Lanka's famous deposits, set in 925 sterling silver with rhodium plating. Classic oval cabochon with signature blue sheen.",
    price: "$25 – $80",
    priceMin: 25,
    priceMax: 80,
    unit: "/piece",
    minOrder: "10 pcs MOQ",
    minOrderQty: 10,
    moqUnit: "pcs",
    supplier: "Moonstone Jewellers Lanka",
    supplierId: 6,
    location: "Colombo",
    rating: 4.8,
    reviews: 58,
    badge: "Verified",
    tag: "Trending",
    emoji: "🔮",
    bg: "from-slate-100 to-gray-50",
    certifications: ["925 Sterling Silver Hallmark", "GIA Graduate"],
    leadTime: "7–10 days",
    paymentTerms: "T/T, L/C, PayPal",
    packaging: "Velvet jewelry box, OPP bag, gift wrap available",
    specifications: {
      Stone: "Natural Ceylon Moonstone",
      Metal: "925 Sterling Silver with Rhodium",
      Cut: "Oval Cabochon",
      "Stone Size": "8×10 mm / 10×12 mm / 12×16 mm",
      Adularescence: "Blue sheen",
      Weight: "3–5 g per piece",
    },
    images: ["🔮", "💎", "✨", "🌙"],
    inStock: true,
    views: 660,
    inquiries: 43,
  },
  {
    id: 7,
    slug: "virgin-coconut-oil-cold-pressed",
    category: "Spices & Agriculture",
    categorySlug: "spices-agriculture",
    name: "Virgin Coconut Oil – Cold-Pressed Export Grade",
    description:
      "Pure VCO cold-pressed from fresh mature coconuts within 2 hours of dehusking. No heat, no chemicals. Exported to EU, USA, and Japan with full organic certification.",
    price: "$2.50 – $5",
    priceMin: 2.5,
    priceMax: 5,
    unit: "/litre",
    minOrder: "500 L MOQ",
    minOrderQty: 500,
    moqUnit: "litres",
    supplier: "Coconut Lanka Exports",
    supplierId: 7,
    location: "Gampaha",
    rating: 4.7,
    reviews: 156,
    badge: "Top Supplier",
    tag: "Organic",
    emoji: "🥥",
    bg: "from-lime-100 to-green-50",
    certifications: ["USDA Organic", "EU Organic", "Halal", "Kosher"],
    leadTime: "14–21 days",
    paymentTerms: "T/T, L/C",
    packaging: "1 L PET / 5 L HDPE / 200 L drums",
    specifications: {
      Type: "Virgin Coconut Oil (VCO)",
      Method: "Cold-pressed, wet-milled",
      FFA: "≤ 0.1 %",
      Moisture: "≤ 0.1 %",
      "Peroxide Value": "≤ 1 meq/kg",
      "Lauric Acid": "≥ 48 %",
    },
    images: ["🥥", "🌿", "✨", "💧"],
    inStock: true,
    views: 1890,
    inquiries: 134,
  },
  {
    id: 8,
    slug: "dried-maldive-fish-tuna",
    category: "Seafood & Marine",
    categorySlug: "seafood-marine",
    name: "Dried Maldive Fish (Tuna) – Export Grade",
    description:
      "Premium Maldive fish (dried skipjack tuna) from Sri Lanka's Negombo fishing district. Strong umami flavour, essential in Sri Lankan and Maldivian cuisine. HACCP-certified processing facility.",
    price: "$10 – $18",
    priceMin: 10,
    priceMax: 18,
    unit: "/kg",
    minOrder: "100 kg MOQ",
    minOrderQty: 100,
    moqUnit: "kg",
    supplier: "Lanka Marine Exports",
    supplierId: 8,
    location: "Negombo",
    rating: 4.5,
    reviews: 33,
    badge: "Verified",
    tag: "Fresh",
    emoji: "🐟",
    bg: "from-cyan-100 to-sky-50",
    certifications: ["HACCP", "ISO 22000", "EU Approved"],
    leadTime: "7–14 days",
    paymentTerms: "T/T, L/C",
    packaging: "Vacuum sealed 1 kg / 5 kg bags, cartons of 20 kg",
    specifications: {
      Species: "Skipjack Tuna (Katsuwonus pelamis)",
      Process: "Sun-dried / Smoke-dried",
      Moisture: "≤ 25 %",
      Salt: "≤ 3 %",
      Form: "Whole / Chunks / Flaked",
      Grade: "A / B / C",
    },
    images: ["🐟", "🌊", "🍽️", "🏖️"],
    inStock: true,
    views: 340,
    inquiries: 22,
  },
  {
    id: 9,
    slug: "ayurvedic-herbal-coconut-soap",
    category: "Beauty & Personal Care",
    categorySlug: "beauty-care",
    name: "Ayurvedic Herbal Coconut Soap – Natural Formula",
    description:
      "Cold-process handmade soap infused with Sri Lankan herbs including turmeric, neem, and sandalwood in a virgin coconut oil base. No SLS, parabens, or artificial fragrances.",
    price: "$1.50 – $4",
    priceMin: 1.5,
    priceMax: 4,
    unit: "/bar",
    minOrder: "500 bars MOQ",
    minOrderQty: 500,
    moqUnit: "bars",
    supplier: "Pure Ceylon Beauty",
    supplierId: 9,
    location: "Colombo",
    rating: 4.7,
    reviews: 91,
    badge: "Verified",
    tag: "Organic",
    emoji: "🧴",
    bg: "from-yellow-100 to-amber-50",
    certifications: ["USDA Organic", "Cruelty-Free", "Halal"],
    leadTime: "14–20 days",
    paymentTerms: "T/T, PayPal",
    packaging: "Kraft paper wrap, 100 g / 150 g bars",
    specifications: {
      "Base Oil": "Virgin Coconut Oil",
      "Active Herbs": "Turmeric, Neem, Sandalwood",
      Weight: "100 g / 150 g per bar",
      pH: "8.5–9.5",
      "Shelf Life": "24 months",
      Process: "Cold-process handmade",
    },
    images: ["🧴", "🌿", "✨", "💛"],
    inStock: true,
    views: 540,
    inquiries: 38,
  },
  {
    id: 10,
    slug: "teak-wooden-elephant-sculpture",
    category: "Handicrafts & Arts",
    categorySlug: "handicrafts-arts",
    name: "Hand-Carved Teak Elephant Sculpture",
    description:
      "Traditional Sri Lankan hand-carved elephant figurines from FSC-certified teak wood. Handpainted with non-toxic lacquers. A classic Sri Lankan souvenir and gift export item.",
    price: "$8 – $50",
    priceMin: 8,
    priceMax: 50,
    unit: "/piece",
    minOrder: "50 pcs MOQ",
    minOrderQty: 50,
    moqUnit: "pcs",
    supplier: "Lanka Wood Crafts",
    supplierId: 10,
    location: "Kandy",
    rating: 4.6,
    reviews: 73,
    badge: "Verified",
    tag: "Artisan",
    emoji: "🐘",
    bg: "from-stone-100 to-amber-50",
    certifications: ["FSC Certified", "Fair Trade"],
    leadTime: "14–21 days",
    paymentTerms: "T/T, PayPal",
    packaging: "Bubble wrap + cardboard box, foam lined",
    specifications: {
      Material: "FSC-certified Teak Wood",
      Finish: "Hand-painted with non-toxic lacquer",
      Sizes: "S (4 cm) / M (8 cm) / L (15 cm) / XL (25 cm)",
      Weight: "50–500 g depending on size",
      Origin: "Kandy, Sri Lanka",
      Customization: "Colors, size, plain/painted available",
    },
    images: ["🐘", "🪵", "🎨", "✨"],
    inStock: true,
    views: 820,
    inquiries: 56,
  },
  {
    id: 11,
    slug: "organic-black-pepper-export",
    category: "Spices & Agriculture",
    categorySlug: "spices-agriculture",
    name: "Organic Black Pepper – Export Grade (Whole/Ground)",
    description:
      "Premium Sri Lankan black pepper from the Matale and Kandy districts. High piperine content, strong pungency. Available in whole berries or ground powder. Certified organic.",
    price: "$4 – $10",
    priceMin: 4,
    priceMax: 10,
    unit: "/kg",
    minOrder: "50 kg MOQ",
    minOrderQty: 50,
    moqUnit: "kg",
    supplier: "Spice Garden Lanka",
    supplierId: 4,
    location: "Matale",
    rating: 4.8,
    reviews: 112,
    badge: "Top Supplier",
    tag: "Organic",
    emoji: "⚫",
    bg: "from-gray-100 to-slate-50",
    certifications: ["USDA Organic", "EU Organic", "ISO 9001"],
    leadTime: "10–14 days",
    paymentTerms: "T/T, L/C",
    packaging: "25 kg multi-wall paper sacks / 1 kg vacuum packs",
    specifications: {
      Species: "Piper nigrum",
      Piperine: "≥ 4 %",
      Moisture: "≤ 12 %",
      "Bulk Density": "550–650 g/L",
      Forms: "Whole / Cracked / Ground",
      "ASTA Score": "25–35",
    },
    images: ["⚫", "🌿", "🌱", "✨"],
    inStock: true,
    views: 1100,
    inquiries: 78,
  },
  {
    id: 12,
    slug: "ceylon-silver-tips-white-tea",
    category: "Ceylon Tea",
    categorySlug: "ceylon-tea",
    name: "Ceylon Silver Tips White Tea – Premium Grade",
    description:
      "Ultra-premium hand-picked silver tips (young buds) from high-altitude Nuwara Eliya estates. Light floral liquor with delicate sweetness. Limited seasonal harvest – January only.",
    price: "$80 – $200",
    priceMin: 80,
    priceMax: 200,
    unit: "/kg",
    minOrder: "5 kg MOQ",
    minOrderQty: 5,
    moqUnit: "kg",
    supplier: "Dilmah Exports Pvt Ltd",
    supplierId: 1,
    location: "Nuwara Eliya",
    rating: 4.9,
    reviews: 45,
    badge: "Top Supplier",
    tag: "Premium",
    emoji: "☕",
    bg: "from-gray-50 to-slate-50",
    certifications: ["Rainforest Alliance", "ISO 22000", "UTZ Certified"],
    leadTime: "7–14 days",
    paymentTerms: "T/T, L/C",
    packaging: "Airtight foil bags, gift tin available",
    specifications: {
      Grade: "Silver Tips / Golden Tips",
      Flush: "First flush (Jan–Feb only)",
      Altitude: "2,000–2,200 m",
      Picking: "Hand-picked young buds",
      Processing: "Minimal (sun-withered only)",
      Antioxidants: "Very high EGCG content",
    },
    images: ["☕", "🍃", "✨", "🌸"],
    inStock: false,
    views: 670,
    inquiries: 52,
  },
];

export const SUPPLIERS = [
  {
    id: 1,
    slug: "dilmah-exports",
    name: "Dilmah Exports Pvt Ltd",
    category: "Ceylon Tea",
    categorySlug: "ceylon-tea",
    location: "Colombo",
    established: 1988,
    employees: "500–1000",
    rating: 4.9,
    reviews: 312,
    responseTime: "< 2 hrs",
    responseRate: "98%",
    badge: "Gold Supplier",
    emoji: "🫖",
    bg: "bg-emerald-100",
    description:
      "Sri Lanka's most recognised tea brand and export house. Supplying premium Ceylon tea to over 100 countries since 1988. ISO 22000 and Rainforest Alliance certified processing.",
    certifications: ["ISO 22000", "HACCP", "Rainforest Alliance", "UTZ"],
    mainProducts: ["BOP Tea", "BOPF Tea", "Silver Tips", "Green Tea", "White Tea"],
    exportCountries: 100,
    annualRevenue: "$50M+",
    verified: true,
    productCount: 24,
  },
  {
    id: 2,
    slug: "lanka-gem-bureau",
    name: "Lanka Gem Bureau Ltd",
    category: "Gems & Jewelry",
    categorySlug: "gems-jewelry",
    location: "Ratnapura",
    established: 1971,
    employees: "100–200",
    rating: 4.9,
    reviews: 178,
    responseTime: "< 4 hrs",
    responseRate: "95%",
    badge: "Gold Supplier",
    emoji: "💎",
    bg: "bg-blue-100",
    description:
      "Sri Lanka's premier gem trading and export bureau. Government-registered gem dealers with GIA-certified graders on staff. Trusted by international jewellers for over 50 years.",
    certifications: ["GIA Graduate", "SLTB Registered", "AGL Report"],
    mainProducts: ["Blue Sapphire", "Ruby", "Cat's Eye", "Moonstone", "Alexandrite"],
    exportCountries: 65,
    annualRevenue: "$10M+",
    verified: true,
    productCount: 86,
  },
  {
    id: 3,
    slug: "lanka-batik-creations",
    name: "Lanka Batik Creations",
    category: "Apparel & Textiles",
    categorySlug: "apparel-textiles",
    location: "Kandy",
    established: 2003,
    employees: "50–100",
    rating: 4.7,
    reviews: 98,
    responseTime: "< 6 hrs",
    responseRate: "92%",
    badge: "Verified Supplier",
    emoji: "🧵",
    bg: "bg-purple-100",
    description:
      "Specialist in traditional Sri Lankan handloom and batik textiles. GOTS certified with artisan partnerships across the central highlands of Sri Lanka.",
    certifications: ["GOTS Certified", "OEKO-TEX Standard 100", "Fair Trade"],
    mainProducts: ["Batik Fabric", "Handloom Sarees", "Tie-Dye Cotton", "Dumbara Weave"],
    exportCountries: 30,
    annualRevenue: "$2M+",
    verified: true,
    productCount: 38,
  },
  {
    id: 4,
    slug: "spice-garden-lanka",
    name: "Spice Garden Lanka",
    category: "Spices & Agriculture",
    categorySlug: "spices-agriculture",
    location: "Matara",
    established: 1995,
    employees: "200–500",
    rating: 4.8,
    reviews: 267,
    responseTime: "< 3 hrs",
    responseRate: "97%",
    badge: "Gold Supplier",
    emoji: "🌿",
    bg: "bg-amber-100",
    description:
      "Leading exporter of organic Ceylon spices. Operates certified organic spice farms and a modern processing facility in Matara. USDA and EU organic certified.",
    certifications: ["USDA Organic", "EU Organic", "ISO 9001", "HACCP"],
    mainProducts: ["True Cinnamon", "Black Pepper", "Cardamom", "Cloves", "Turmeric"],
    exportCountries: 55,
    annualRevenue: "$8M+",
    verified: true,
    productCount: 52,
  },
  {
    id: 5,
    slug: "village-craft-collective",
    name: "Village Craft Collective",
    category: "Handicrafts & Arts",
    categorySlug: "handicrafts-arts",
    location: "Kurunegala",
    established: 2008,
    employees: "20–50",
    rating: 4.6,
    reviews: 54,
    responseTime: "< 12 hrs",
    responseRate: "88%",
    badge: "Verified Supplier",
    emoji: "🏺",
    bg: "bg-orange-100",
    description:
      "A cooperative of 200+ rural artisans producing traditional Sri Lankan handicrafts. Fair-trade certified, supporting sustainable village livelihoods since 2008.",
    certifications: ["WFTO Member", "Fair Trade USA"],
    mainProducts: ["Dumbara Mats", "Pottery", "Cane Baskets", "Lacquerware"],
    exportCountries: 20,
    annualRevenue: "$500K+",
    verified: true,
    productCount: 67,
  },
  {
    id: 6,
    slug: "moonstone-jewellers-lanka",
    name: "Moonstone Jewellers Lanka",
    category: "Gems & Jewelry",
    categorySlug: "gems-jewelry",
    location: "Colombo",
    established: 1999,
    employees: "20–50",
    rating: 4.8,
    reviews: 72,
    responseTime: "< 4 hrs",
    responseRate: "94%",
    badge: "Verified Supplier",
    emoji: "🔮",
    bg: "bg-slate-100",
    description:
      "Specialist jewellery manufacturer combining Ceylon gemstones with precious metals. Custom OEM jewellery for international brands and private label buyers.",
    certifications: ["925 Sterling Silver Hallmark", "GIA Graduate Gemologists"],
    mainProducts: ["Moonstone Jewelry", "Sapphire Pendants", "Gem Rings", "Custom OEM"],
    exportCountries: 35,
    annualRevenue: "$1.5M+",
    verified: true,
    productCount: 43,
  },
  {
    id: 7,
    slug: "coconut-lanka-exports",
    name: "Coconut Lanka Exports",
    category: "Coconut Products",
    categorySlug: "coconut-products",
    location: "Gampaha",
    established: 2001,
    employees: "100–200",
    rating: 4.7,
    reviews: 189,
    responseTime: "< 4 hrs",
    responseRate: "96%",
    badge: "Gold Supplier",
    emoji: "🥥",
    bg: "bg-lime-100",
    description:
      "Full-range coconut product exporter. From virgin coconut oil to activated charcoal, desiccated coconut, and coir products.",
    certifications: ["USDA Organic", "EU Organic", "Halal", "Kosher", "ISO 22000"],
    mainProducts: ["Virgin Coconut Oil", "Desiccated Coconut", "Coconut Sugar", "Coir Fibre"],
    exportCountries: 48,
    annualRevenue: "$5M+",
    verified: true,
    productCount: 31,
  },
  {
    id: 8,
    slug: "lanka-marine-exports",
    name: "Lanka Marine Exports",
    category: "Seafood & Marine",
    categorySlug: "seafood-marine",
    location: "Negombo",
    established: 1992,
    employees: "50–100",
    rating: 4.5,
    reviews: 41,
    responseTime: "< 8 hrs",
    responseRate: "90%",
    badge: "Verified Supplier",
    emoji: "🐟",
    bg: "bg-cyan-100",
    description:
      "HACCP-certified seafood processor and exporter based in Negombo. Specialising in dried and value-added tuna products for the Middle East and EU markets.",
    certifications: ["HACCP", "ISO 22000", "EU Approved Establishment"],
    mainProducts: ["Maldive Fish", "Canned Tuna", "Dried Prawns", "Fish Meal"],
    exportCountries: 25,
    annualRevenue: "$2M+",
    verified: true,
    productCount: 18,
  },
];

export const LOCATIONS = [
  "Colombo", "Kandy", "Ratnapura", "Matara", "Gampaha",
  "Negombo", "Kurunegala", "Nuwara Eliya", "Matale", "Galle",
  "Hambantota", "Kalutara",
];

export const CERTIFICATIONS = [
  "USDA Organic", "EU Organic", "ISO 22000", "HACCP",
  "Fair Trade", "GIA Certified", "GOTS Certified", "Halal",
  "Kosher", "Rainforest Alliance",
];

export const TAG_COLORS = {
  Hot:      "bg-red-500",
  Premium:  "bg-purple-600",
  New:      "bg-blue-500",
  Organic:  "bg-green-600",
  Artisan:  "bg-amber-600",
  Trending: "bg-pink-500",
  Fresh:    "bg-cyan-600",
};
